CREATE DATABASE IF NOT EXISTS telecom_analytics CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE telecom_analytics;

CREATE TABLE IF NOT EXISTS ue_measurements (
  timestamp_utc DATETIME NOT NULL,
  ue_id VARCHAR(32) NOT NULL,
  serving_cell_id VARCHAR(32) NOT NULL,
  beam_id VARCHAR(16) NOT NULL,
  rsrp_dbm DOUBLE,
  rsrq_db DOUBLE,
  sinr_db DOUBLE,
  cqi INT,
  rank_indicator INT,
  mcs_index INT,
  bler_dl_pct DOUBLE,
  timing_advance DOUBLE,
  dl_throughput_mbps DOUBLE,
  ul_throughput_mbps DOUBLE,
  handover_event VARCHAR(8),
  velocity_kph DOUBLE,
  packet_loss_pct DOUBLE,
  latency_ms DOUBLE,
  jitter_ms DOUBLE,
  harq_retx_pct DOUBLE,
  device_profile VARCHAR(64),
  service_type VARCHAR(64),
  traffic_load_mb DOUBLE,
  neighbor_cell_count INT,
  beam_switch_count INT,
  KEY idx_ue_timestamp (timestamp_utc),
  KEY idx_ue_cell_beam (serving_cell_id, beam_id),
  KEY idx_ue_id (ue_id)
);

CREATE TABLE IF NOT EXISTS beam_kpis (
  window_start_utc DATETIME NOT NULL,
  cell_id VARCHAR(32) NOT NULL,
  beam_id VARCHAR(16) NOT NULL,
  active_ue_count INT,
  avg_rsrp_dbm DOUBLE,
  avg_rsrq_db DOUBLE,
  avg_sinr_db DOUBLE,
  prb_utilization_pct DOUBLE,
  beam_utilization_pct DOUBLE,
  dl_retransmission_pct DOUBLE,
  scheduled_dl_mbps DOUBLE,
  scheduled_ul_mbps DOUBLE,
  avg_bler_dl_pct DOUBLE,
  handover_attempts INT,
  handover_failures INT,
  beam_switch_success_rate_pct DOUBLE,
  radio_link_failure_count INT,
  cell_edge_ue_ratio DOUBLE,
  interference_score DOUBLE,
  power_headroom_db DOUBLE,
  scheduler_pressure_score DOUBLE,
  PRIMARY KEY (window_start_utc, cell_id, beam_id),
  KEY idx_beam_cell (cell_id, beam_id)
);
